### ISSUE TITLE
Create recipes index page

### ISSUE THREAD

**Issue by yrezgui** [busybeeL/recipes#2]
Can you create an index page looking like my mockup?
The page has to be designed in CSS and written only in HTML.

![photo5864070887232352939](https://user-images.githubusercontent.com/1113976/80814396-b765b100-8bc3-11ea-97e4-3ce34a5ea2a1.jpg)

**Comment by yrezgui** [comment]
Changes added here: https://github.com/busybeeL/recipes/commit/8c7d3f0c93801a1ef22dd204d57e2648dac4f361

**Comment by yrezgui** [comment]
Great work! Here are some issues to fix and we're good to go to the second part:

* Add `.DS_Store` to your .gitignore. These files are Mac OS system files and are not needed to be committed https://github.com/busybeeL/recipes/commit/8c7d3f0c93801a1ef22dd204d57e2648dac4f361#diff-b258b65203e895dbb6c8ef99e3c340cf
* We will use a packager to avoid putting Bootstrap source directly in your own project source code. I've created an issue to track it https://github.com/busybeeL/recipes/issues/3

**Comment by busybeeL** [comment]
Hi @yrezgui I've added .DS_Store in .gitignore and install bootstrap package into the project folder. I've tried to change the path for css like this
"/node_modules/bootstrap/dist/css/bootstrap.css" 
but it didn't work. so I copied all bootstrap css files into our css folder. please let me know if there anything I can improve my code. Thank you!
